version: '3'
services:
  redis:
    image: redis:alpine
    restart: always

  proxy:
    build: ./
    networks:
      - site1
      - site2
    ports:
      - 72:80
    depends_on:
      - redis
  php:
    image: nanoninja/php-fpm:${PHP_VERSION}
    restart: always
    volumes:
      - "./php.ini:/usr/local/etc/php/conf.d/php.ini"
      - ".:/var/www/html"

    depends_on:
      - redis
      - proxy
  mariadb:
    image: mariadb:${MYSQL_VERSION}
    container_name: ${MYSQL_HOST}
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
    volumes:
      - "./data/mysql:/var/lib/mysql"
networks:
  site1:
    external:
      name: site1_default
  site2:
    external:
      name: site2_default
